class MessageType:
    REQUEST_REGISTER, REQUEST_FILE_LIST, REQUEST_FILE_LOCATION, REQUEST_CHUNK_REGISTER, REQUEST_LEAVE, \
    REPLY_PEER_LIST, REPLY_REGISTER, REPLY_FILE_LIST, REPLY_FILE_LOCATION, REPLY_CHUNK_REGISTER, REPLY_LEAVE, \
    PEER_REQUEST_CHUNK, PEER_REPLY_CHUNK = range(13)
